SRC = main.cpp ClapTrap.cpp ScavTrap.cpp FragTrap.cpp DiamondTrap.cpp

CC = c++

FLAGS = -Wall -Wextra -Werror -Wshadow -Wno-shadow -std=c++98

all : 
	$(CC) $(FLAGS) $(SRC)

fclean :
	rm -rf a.out

re : 
	rm -rf a.out
	make all